name: Build & Deploy rcfg.xyz

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Zip the site
      - name: Archive site
        run: zip -r site.zip .

      # Copy the ZIP to your server
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "site.zip"
          target: "/tmp/"

      # SSH in and run your deploy script
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo /root/deploy_rcfg.sh
